---
- hosts: all
  remote_user: ubuntu
  become: yes

  tasks:
    - name: Set authorized keys taken from url
      become: no
      authorized_key:
        user: ubuntu
        state: present
        key: https://github.com/jsoppela.keys

    - name: Ensure RSA keypair exists
      become: bi
      openssh_keypair:
        path: /home/ubuntu/.ssh/id_rsa

    - name: Sync Meerkat Nest repo
      become: no
      git:
        repo: https://github.com/fjelltopp/meerkat_nest.git
        dest: /home/ubuntu/meerkat_nest
        accept_hostkey: yes

    - name: Sync Meerkat Drill repo
      become: no
      git:
        repo: https://github.com/fjelltopp/meerkat_drill.git
        dest: /home/ubuntu/meerkat_drill
        accept_hostkey: yes

    - include_role:
        name: "nickjj.docker"